Remove cache.h include
cache.h was removed.

-----
    CC compat/os2.o
compat/os2.c:31:10: fatal error: ../cache.h: No such file or directory
   31 | #include "../cache.h"
      |          ^~~~~~~~~~~~
-----